import React from 'react';
import $ from 'jquery';
import CommentList from './commentlist.jsx';
import CommentForm from './commentform.jsx';

export default class CommentBox extends React.Component {
    constructor() {
        super();

        this.state = { data: [] };

        this.handleCommentSubmit = this.bind(this);
    }

    componentDidMount() {
        this.loadCommentsFromServer();
        setInterval(() => this.loadCommentsFromServer(), this.props.pollInterval);
    }

    loadCommentsFromServer() {
        $.ajax({
            url: this.props.url,
            dataType: 'json',
            cache: false,
            success: (data) => {
                this.setState({ data });
            },
            error: (xhr, status, err) => {
                /* eslint-disable no-console */
                console.error(this.props.url, status, err.toString());
                /* eslint-enable no-console */
            },
        });
    }

    handleCommentSubmit(comment) {
        const comments = this.state.data;
        // Optimistically set an id on the new comment. It will be replaced by an
        // id generated by the server. In a production application you would likely
        // not use Date.now() for this and would have a more robust system in place.
        comment.id = Date.now();
        const newComments = comments.concat([comment]);
        this.setState({ data: newComments });

        $.ajax({
            url: this.props.url,
            dataType: 'json',
            type: 'POST',
            data: comment,
            success: (data) => {
                this.setState({ data });
            },
            error: (xhr, status, err) => {
                // this.setState({data: comments});
                /* eslint-disable no-console */
                console.error(this.props.url, status, err.toString());
                /* eslint-enable no-console */
            },
        });
    }

    render() {
        return (
            <div className='commentBox'>
                <h1>Comments</h1>
                <CommentList data={this.state.data} />
                <CommentForm onCommentSubmit={this.handleCommentSubmit} />
            </div>
        );
    }
}


CommentBox.propTypes = {
    url: React.PropTypes.string,
    pollInterval: React.PropTypes.number,
};
